apiVersion: v1
kind: Pod
metadata:
  name: test-env
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: kubernates
        - name: trainer
          value: shiva
# using this we can set environemt variables
      resources:
        requests:
          cpu: "120m"
          memory: "68Mi"
        limits:
          cpu: "240m"
          memory: "120Mi"
# if we not allocate resources it consumes entire node resources accidentally.
