apiVersion: v1
kind: Secret
metadata:
  name: secret-01
type: Opaque
data:
  username: "YWRtaW4K"
  password: "YWRtaW4xMjMK"
---
apiVersion: v1
kind: pod-secretes
metadata:
  name: pod-01
spec:
  containers:
    - name: nginx
      image: nginx
      envFrom:
        - secretRef:
            name: secret-01
