apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp
spec:
  replicas: 2
  selector:
    matchLabels:
      project: c1
      manager: vimal
      client: kvb
  template:
    metadata:
      labels:
        project: c1
        manager: vimal
        client: kvb
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.2 # this is old
          imagePullPolicy: Always
          #image: nginx # latest image
          ports:
            - protocol: TCP
              containerPort: 80              
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3


  